apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstrun-api
spec:
  template:
    spec:
      volumes:
        - name: config-dir
          configMap:
            name: firstrun-config
      containers:
        - name: firstrun-api
          args: ["api", "--log-level", "debug"]
          volumeMounts:
            - name: firstrun-config
              mountPath: /root/firstrun
