apiVersion: v1
kind: Service
metadata:
  name: firstrun-api
  labels:
    app: firstrun-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: firstrun-api
