FROM node:16-bullseye
EXPOSE 3000 9229

RUN apt update && apt install -y apt-transport-https ca-certificates sqlite3

ARG OKTETO_NAMESPACE=okteto

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

ENTRYPOINT ["yarn", "dev"]
