apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstrun-frontend
spec:
  template:
    spec:
      containers:
        - name: firstrun-frontend
          ports:
            - name: http
              containerPort: 3000
