apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: firstrun
spec:
  template:
    spec:
      volumes:
      - name: firstrun-config
        configMap:
          name: firstrun-config
      containers:
        - name: firstrun
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: firstrun-config
              mountPath: /firstrun/config
