name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - id: prep-image
        run: |
          DOCKER_IMAGE=ghcr.io/firstrunapp/firstrun/firstrun
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1.10.0
        name: log in to docker registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./firstrun
          tags: ${{ steps.prep-image.outputs.tags }}
          file: ./deploy/Dockerfile.frontend
          push: true

